name: Build & Push to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: oudarjateamalpha
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker buildx build --platform linux/amd64 -t oudarjateamalpha/house-prediction:latest --load .

      - name: Push Docker Image
        run: docker push oudarjateamalpha/house-prediction:latest
